# *******************************************************************************
# * Copyright (C) 2017-2025 German Aerospace Center (DLR). 
# * Eclipse ADORe, Automated Driving Open Research https://eclipse.org/adore
# *
# * This program and the accompanying materials are made available under the 
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0 
# *
# * Contributors: 
# *   Marko Mizdrak
# ********************************************************************************
float64 cog_to_front_axle # m
float64 rear_axle_to_cog # m
float64 wheelbase # m
float64 front_axle_to_front_border # m
float64 rear_border_to_rear_axle # m
float64 mass # kg
float64 friction_coefficient # N/(m/s)
float64 cog_height # m
float64 front_tire_stiffness 
float64 rear_tire_stiffness
float64 rotational_inertia_div_mass
float64 front_track_width # m
float64 rear_track_width # m
float64 steering_ratio 
float64 steering_angle_max # rad
float64 steering_angle_min # rad
float64 acceleration_min # m/s^2
float64 acceleration_max # m/s^2
float64 cornering_stiffness # N/rad
float64 brake_balance_front # %
float64 acceleration_balance_front # %
float64 body_width # m
float64 body_length # m
float64 body_height # m
