# *******************************************************************************
# * Copyright (C) 2017-2025 German Aerospace Center (DLR). 
# * Eclipse ADORe, Automated Driving Open Research https://eclipse.org/adore
# *
# * This program and the accompanying materials are made available under the 
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0 
# *
# * Contributors: 
# *   Marko Mizdrak
# ********************************************************************************
float64 cog_to_front_axle
float64 rear_axle_to_cog
float64 wheelbase
float64 front_axle_to_front_border
float64 rear_border_to_rear_axle
float64 mass
float64 friction_coefficient
float64 cog_height
float64 front_tire_stiffness
float64 rear_tire_stiffness
float64 rotational_inertia_div_mass
float64 front_track_width
float64 rear_track_width
float64 steering_ratio
float64 steering_angle_max
float64 steering_angle_min
float64 cornering_stiffness
float64 brake_balance_front
float64 acceleration_balance_front
float64 body_width
float64 body_length
float64 body_height
