# *******************************************************************************
# * Copyright (C) 2017-2025 German Aerospace Center (DLR). 
# * Eclipse ADORe, Automated Driving Open Research https://eclipse.org/adore
# *
# * This program and the accompanying materials are made available under the 
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0 
# *
# * Contributors: 
# *   Marko Mizdrak
# ********************************************************************************
# VehicleInfo.msg
GearState gear_state
float64 wheel_speed
bool left_indicator_on
bool right_indicator_on
bool automatic_steering_on
bool automatic_acceleration_on
bool automatic_acceleration_active
bool clearance
