# *******************************************************************************
# * Copyright (C) 2017-2025 German Aerospace Center (DLR). 
# * Eclipse ADORe, Automated Driving Open Research https://eclipse.org/adore
# *
# * This program and the accompanying materials are made available under the 
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0 
# *
# * Contributors: 
# *   Marko Mizdrak
# ********************************************************************************

# VehicleStateDynamic.msg
float64 x
float64 y
float64 z
float64 vx
float64 vy
float64 yaw_angle
float64 yaw_rate
float64 steering_angle
float64 steering_rate
float64 ax
float64 ay
float64 time
